# wrangler.toml
name = "child-math"
compatibility_date = "2023-01-01"

[env.production]
routes = [
  { pattern = "/*", script = "" }
]

[env.production.site]
spa = true

[env.staging]
routes = [
  { pattern = "/*", script = "" }
]

[env.staging.site]
spa = true